### ISSUE TITLE
All Source Code Downloads from Main Boost Site Return 403 Forbidden

### ISSUE THREAD

**Issue by marko-kovacevic** [boostorg/boost#502]
Hello,

Wanted to bring to the attention of the people that manage the Boost website - multiple source code version downloads are returning 403 forbidden error when trying to download.

Example, when I wget https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz

Or when I visit the following
https://dl.bintray.com/boostorg/release/1.74.0/source/

Thanks!

**Comment by mclow** [comment]
BinTray is closing soon; we're in the process of moving to JFrog Artifactory.  For 1.74.0 releases, you can use https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.tar.gz

**Comment by mclow** [comment]
That should be the stable home; but we're still working on it.

**Comment by userdocs** [comment]
Is there a reason you don't use git actions + releases for hosting the archives (not the git source)?

**Comment by mclow** [comment]
Yes; because we get *a lot* of downloads. Our bandwidth quota on BinTray kept getting raised until we no longer ran out every month, and it's such a large number that we don't want to just drop that load on a provider w/o discussion.

**Comment by userdocs** [comment]
I am not aware of any specific limitation documented or enforced by Github. I found this for example [https://github.community/t/restrictions-on-released-binaries/749/2](https://github.community/t/restrictions-on-released-binaries/749/2) but I am not sure what applies to a prjoect of your size.

Thanks for the reply. I was just curious to know.

**Comment by mclow** [comment]
If we had to pay for the bandwidth used for boost downloads, it would be several thousand $$/month.  We appreciate that JFrog is willing to provide this to us for free.

**Comment by userdocs** [comment]
Ok so I was thinking about this. Looking at stats for the last 30 days:

Bintray https://bintray.com/boostorg/release/boost-binaries#statistics

2,488 mixed downloads. (which I guess was the limited by the bandwidth allowance)

Sourceforge https://sourceforge.net/projects/boost/files/stats/timeline?dates=2021-03-14+to+2021-04-13

138,429 mixed downloads

The majority of downloads are from the source files and not binaries. (8.5% of 32,398 = approx 2753?)

Assume some generous averages and define some values:

- 1GB - 1000MB
- 1TB - 1000GB
- 150MB per download
- 150k average downloads per month for Sourceforge.
- 5k average downloads per month for bintray (50% through the month so we could assume we need twice the 2.5k amount to supply a month)

```
5000 downloads x 150MB = 750000MB / 1000 = 750GB / 1000 = 0.75TB per 30 days @ bintray
```
```
150000 downloads x 150MB = 22,500,000MB / 1000 = 22500GB / 1000 = 22.5TB per 30 days @ sourceforge
```

So that works that Soureforge is currently doing the most work. So by adding Github releases you would not be increasing this load on another provider but simply shifting some of the load to github.

So if the new site jfrog.io follows in this pattern we would see something like this?

- jfrog.io = 1TB per month
- Soureforge = 15TB per month
- Github = 15TB per month.

Even if for some weird reason github took the full burden it will be at best 30TB a month. That does not cost a huge amount per month.

If Soureforge can handle it I am sure it github can handle it, unless I have calculated everything wrong?

I just want github releases since i'd find it more reliable an inline with what i'm already doing.

**Comment by userdocs** [comment]
I used the wrong figure for bintray (binary only) I have updated and corrected.

**Comment by rothn** [comment]
This is still happening

**Comment by mclow** [comment]
We moved off of binary nine months ago. Please use jFrog instead. The links are on the boost website.

**Comment by rayrapetyan** [comment]
> BinTray is closing soon; we're in the process of moving to JFrog Artifactory. For 1.74.0 releases, you can use https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.tar.gz
Could we not use both underscores and dots in the URL? This is really annoying especially for scripts which do not support basic string substitutions (e.g. Dockerfile) to define two similar vars like: 
```
ARG BOOST_VER_UNDERSCORED=1_74_0
ARG BOOST_VER_DOTTED=1.74.0
```

**Comment by Killtutor** [comment]
jfrog keeps forbidden downloads

**Comment by sdarwin** [comment]
@Killtutor jfrog seems to be working.  You are welcome to provide a more detailed bug report.

**Comment by Killtutor** [comment]
<img width="711" alt="image" src="https://github.com/boostorg/boost/assets/20267814/259f21a0-39a6-4317-a950-10fccc981cf4">

**Comment by Killtutor** [comment]
alfin pude descargarlo

**Comment by Killtutor** [comment]
sorry.. Finally.. it finish the download
